name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build & Test
    runs-on: macos-latest
    strategy:
      matrix:
      destination: ['platform=iOS Simulator,OS=13.5,name=iPhone 11']
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: xcodebuild clean build -project Calculator\ Layout\ iOS13.xcodeproj -scheme Calculator\ Layout\ iOS13 -destination "${destination}"
      - name: Run tests
        run: swift test -v
